# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
