# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170302_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='paypal',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
